[package]
name = "survival_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
rand = "0.8.5"
getrandom = { version = "0.2.5", features = ["js"] }
bevy-inspector-egui = { version = "0.9.0" }